<!DOCTYPE html>
<html lang="pt-BR">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Voluntarie.se | Alterar Senha</title>
    <link rel="apple-touch-icon" sizes="180x180" href="img/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="img/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="img/favicon-16x16.png">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="bootstrap-5.0.0-beta2-dist/bootstrap-5.0.0-beta2-dist/css/bootstrap.min.css" rel="stylesheet"
        type="text/css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css"
        integrity="sha512-HK5fgLBL+xu6dm/Ii3z4xhlSUyZgTT9tuc/hSrtw6uzJOvgRr2a9jyxxT1ely+B+xFAmJKVSTbpM/CuL7qxO8w=="
        crossorigin="anonymous" />
    <link rel="stylesheet" href="css/alterarSenha.css">
    <link rel="stylesheet" href="cssResp/alterarSenhaResp.css">
    <link rel="stylesheet" href="cssResp/BarraMobResp.css">
    <script type="text/javascript" src="js/jquery-3.5.1.min.js"> </script>
    <script type="text/javascript" src="js/bootstrap.min.js"> </script>
    <script type="text/javascript" src="js/jquery.validate.min.js"> </script>
    <script type="text/javascript" src="js/additional-methods.min.js"> </script>
    <script type="text/javascript" src="js/localization/messages_pt_BR.js"></script>
    <script type="text/javascript" src="js/jquery.mask.min.js"></script>
    <script type="text/javascript" src="JavaScript/alterar_senha.js"></script>
</head>

<body>
    <!-- Alterar Senha -->
    <form class="form" id="alterarSenha" action="/alt_senha" method="POST">
        <div class="alterarSenha">
            <h3 class="text-light text-center">Alterar Senha</h3>
            <div class="mb-2 mt-3">
                <label class="form-label text-light mb-0">Senha Atual</label>
                <input type="password" class="form-control bg-dark text-light p-1" id="senhaAtual" name="senhaAtual">
            </div>
            <div class="mb-2">
                <label class="form-label text-light mb-0">Nova Senha</label>
                <input type="password" class="form-control bg-dark text-light p-1" id="novaSenha" name="novaSenha">
            </div>
            <div class="mb-2">
                <label class="form-label text-light mb-0">Confirmar Senha</label>
                <input type="password" class="form-control bg-dark text-light p-1" id="confirmarSenha" name="confirmarSenha">
            </div>
            <div class="text-center">
                <button type="submit" class="btn btn-light corBotao mt-3">Alterar</button>
            </div>
        </div>
    </form>    
    <!-- (FIM) Alterar Senha -->
</body>

</html>