<!DOCTYPE html>
<html lang="pt-BR">
<head>
 
    <title>Voluntarie.se | Alterar Senha</title>
    <link rel="apple-touch-icon" sizes="180x180" href="img/apple-touch-icon.png">
    <link rel="stylesheet" href="css/alterarSenha.css">
    <link rel="stylesheet" href="cssResp/alterarSenhaResp.css">
    <link rel="stylesheet" href="cssResp/BarraMobResp.css">
    <script type="text/javascript" src="JavaScript/alterar_senha.js"></script>
</head>

<body>

    <?php if ($this->view->senhaAlterada == 'ok') { ?>
        <div class="alert alert-success alert-dismissible w-100" style="position: absolute; top: 8%; text-align: center;" role="alert" >
            <strong class= "mx-auto">Senha alterada com sucesso!</strong>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    <?php }elseif($this->view->senhaAlterada == 'nok'){ ?>
        <div class="alert alert-danger alert-dismissible w-100" style="position: absolute; top: 8%; text-align: center;" role="alert" >
            <strong class= "mx-auto">Senha atual Inválida!</strong>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    <?php } ?>    

    <!-- Alterar Senha -->
    <form class="form" id="alterarSenha" action="/alt_senha" method="POST">
        <div class="alterarSenha">
            <h3 class="text-light text-center">Alterar Senha</h3>
            <div class="mb-2 mt-3">
                <label class="form-label text-light mb-0">Senha Atual</label>
                <input type="password" class="form-control bg-dark text-light p-1" id="senhaAtual" name="senhaAtual">
            </div>
            <div class="mb-2">
                <label class="form-label text-light mb-0">Nova Senha</label>
                <input type="password" class="form-control bg-dark text-light p-1" id="novaSenha" name="novaSenha">
            </div>
            <div class="mb-2">
                <label class="form-label text-light mb-0">Confirmar Senha</label>
                <input type="password" class="form-control bg-dark text-light p-1" id="confirmarSenha" name="confirmarSenha">
            </div>
            <div class="text-center">
                <button type="submit" class="btn btn-light corBotao mt-3">Alterar</button>
            </div>
        </div>
    </form>    
    <!-- (FIM) Alterar Senha -->
</body>

</html>