<!DOCTYPE html>
<html lang="pt-BR">

<head>
    <title>Voluntarie.se | Criar Ação</title>
    <link rel="stylesheet" href="css/criarAcao.css">
    <link rel="stylesheet" href="cssResp/criarAcaoResp.css">
    <link rel="stylesheet" href="cssResp/BarraMobResp.css">
    <script src="JavaScript/criar-acao.js"></script>
</head>

<body>

    <!-- Lateral - Dados do usuário(ESQUERDA) -->
    <div class="perfilFiltro">
        <div class="card mt-3 cardEsquerda" id="cardPerfil">
            <?php foreach ($this->view->minha_imagem as $id => $imagem) { ?>
                <div class="card-body">
                    <?php if (file_exists('upload/perfil/'. $imagem['imagem_url'])) { ?>
                        <img src="upload/perfil/<?= $imagem['imagem_url'] ?>" alt="" class="img-fluid rounded-circle" id="fotoPerfil">
                    <?php } else { ?>  
                        <img src="img/íconePerfil.jpg" alt="" class="img-fluid rounded-circle" id="fotoPerfil">  
                    <?php } ?>    
                    <h4 class="mb-5 text-light"><?=$_SESSION['nome']?></h4>
                    <a href="/meu_perfil" class="btn btn-light corBotao mb-4">Meu perfil</a>
                </div>
           <?php }?> 
        </div>
    </div>

    <!-- (FIM)lateral - Dados do usuário(ESQUERDA) -->

    <!-- Formulário de Ação -->
    <div class="formulario">
        <div id="tituloMobile">
            <h3 class="text-light">Criar ação</h3>
        </div>
        <form method="POST" action="/incluir_acao" enctype="multipart/form-data" class="form"> 
        <div class="mb-3">
            <label class="form-label text-light mt-3">Título</label>
            <input type="text" name="titulo" class="form-control bg-dark text-light" id=" exampleFormControlInput1" required>
        </div>
          <div class="mb-3">
            <label class="form-label text-light">Descrição</label>
            <textarea class="form-control bg-dark text-light" name="descricao" id="exampleFormControlTextarea1" rows="3" required></textarea>
          </div>
          <div class="mb-3 w-50 left">
            <label class="form-label text-light">Data</label>
            <input type="datetime-local" class="form-control bg-dark text-light" id="data" name="data_evento" min="2021-06-24T00:00:00" required>
          </div>
          <div class="mb-3 w-50 left">
            <label class="form-label text-light">Categoria</label>
            <select class="form-select bg-dark text-light" aria-label="Default select example" name="categoria" required>
                <option disabled="disabled" selected="selected">-- Selecione uma opção</option>
                <option value="Visitações">Visitações</option>
                <option value="Doação de sangue">Doação de sangue</option>
                <option value="Doação de suprimentos">Doação de suprimentos</option>
                <option value="Distribuição suprimentos">Distribuição suprimentos</option>
                <option value="Adoção de animais">Adoção de animais</option>
                <option value="Passeio com animais">Passeio com animais</option>
            </select>
          </div>
        <div id="quadrado">
            <label for="formFile" class="form-label text-light">Endereço</label>
            <div class="input-group mb-3">
                <input type="text" class="form-control bg-dark text-light" placeholder="Cep" id="cep" required>
                <button class="btn corBotao btn-light" type="button" id="obterEndereco" onclick="endereco()">Obter Endereço</button>
            </div>

            <div class="mb-3">
                <input type="text" class="form-control bg-dark text-light" placeholder="Logradouro" aria-label="Recipient's username" aria-describedby="button-addon2" id="logradouro" name="logradouro" required>
            </div>
            <div class="mb-3">
                <input type="text" class="form-control bg-dark text-light" placeholder="Complemento" aria-label="Recipient's username" aria-describedby="button-addon2" id="complemento" name="complemento">
            </div>
                   
            <div class="mb-3">
                <input type="text" class="form-control bg-dark text-light" placeholder="Bairro" aria-label="Recipient's username" aria-describedby="button-addon2" id="bairro" name="bairro" required>
            </div>

            <div class="mb-3">
                <input type="text" class="form-control bg-dark text-light" placeholder="Cidade" aria-label="Recipient's username" aria-describedby="button-addon2" id="localidade" name="cidade" required>
            </div>

            <div class="mb-3">
                <input type="text" class="form-control bg-dark text-light" placeholder="Estado" aria-label="Recipient's username" aria-describedby="button-addon2" id="uf" name="uf" required>
            </div>            
          </div>

          <div class="mb-3">
            <label for="formFile" class="form-label text-light">Imagem</label>
            <input class="form-control bg-dark text-light" type="file" name="imagem_acao" id="escolherImagem" onchange="previewImagem()">
            <img name="imagem" class="mt-3" id="imagem">
          </div>

          <button class="btn btn-light corBotao"  type="submit" id="botaoCriar">Criar Ação</button>
        </form>
    </div>
    <!-- (FIM) Formulário de Ação -->
</body>

</html>