<!DOCTYPE html>
<html lang="pt-BR">

<head>
    <title>Voluntarie.se | Feed</title>
    <link rel="stylesheet" href="css/feed.css">
    <link rel="stylesheet" href="cssResp/feedResp.css">
    <link rel="stylesheet" href="cssResp/BarraMobResp.css">
    <link rel="stylesheet" href="css/navBarPC.css">
    <script src="/JavaScript/feed.js"></script>
	
	<script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

</head>

<body>
     
    <!-- Lateral - Dados do usuário e filtro de pesquisa(ESQUERDA) -->
    <div class="perfilFiltro">
        <?php if (empty($this->view->minha_imagem)) { ?>
            <div class="card mt-3 cardEsquerda" id="cardPerfil">
                <div class="card-body">
                    <img src="img/íconePerfil.jpg" alt="" class="img-fluid rounded-circle mb-2" id="fotoPerfil">
                    <h4 class="mb-5 text-light"><?=$_SESSION['nome']?></h4>
                    <a href="meu_perfil" class="btn btn-light corBotao mb-4">Meu perfil</a>
                </div>
            </div>
        <?php } else { 
                 foreach ($this->view->minha_imagem as $id => $imagem) { ?>
                    <div class="card mt-3 cardEsquerda" id="cardPerfil">
                        <div class="card-body">
                            <?php if (file_exists('upload/perfil/'. $imagem['imagem_url'])) { ?>
                                <img src="upload/perfil/<?= $imagem['imagem_url'] ?>" alt="" class="img-fluid rounded-circle mb-2" id="fotoPerfil">
                            <?php } else { ?>   
                                <img src="img/íconePerfil.jpg" alt="" class="img-fluid rounded-circle mb-2 fotoCard" id="fotoPerfil">
                            <?php } ?>
                                <h4 class="mb-5 text-light"><?=$_SESSION['nome']?></h4>
                                <a href="meu_perfil" class="btn btn-light corBotao mb-4">Meu perfil</a>
                        </div>
                    </div>
            <?php } ?>
         <?php } ?>               
        <div class="card mt-4 cardEsquerda" id="cardFiltro">
            <form method="POST" action="/filter">
                <div class="card-body filtro">
                    <h6 class="tituloFiltro text-light">Filtro de pesquisa <i class="fas fa-filter"></i></h6>
                    <p class="mt-1 text-light mb-1">Estado:</p>
                    <select class="form-select bg-dark text-light mb-0 p-0" aria-label="Default select example" name="estado" id="estado" onchange="comboxSelect(this)">
                        <option disabled="disabled" selected="selected">-Selecione uma opção</option>
                        <?php foreach($this->view->all_acoes as $id => $acoes) { ?>
                            <?php if(empty($ant)){
                                $ant = array($acoes['uf']);
                            ?>
                            <option value="<?=$acoes['uf']?>"><?=$acoes['uf']?></option>
                            <?php
                            }else{
                                if (!in_array($acoes['uf'], $ant)) {?>          
                                    <option value="<?=$acoes['uf']?>"><?=$acoes['uf']?></option>
                                <?php 
                                $ant[] = $acoes['uf'];
                                } 
                            } ?>
                        <?php }  ?>
                    </select>
                    <p class="text-light mb-1">Cidade:</p>
                    <!--<input type="text" class="form-control bg-dark p-0 text-light" id="cidade" name="cidade">-->
                    <select class="form-select bg-dark text-light mb-0 p-0" aria-label="Default select example" name="cidade" id="cidade">
                        <option disabled="disabled" selected="selected">-Selecione uma opção</option>
                    </select>
                    <p class="mt-1 text-light mb-1">Categoria:</p>
                    <select class="form-select bg-dark text-light p-0 mb-3" aria-label="Default select example" name="categoria" id="categoria">
                        <option disabled="disabled" selected="selected">-Selecione uma opção</option>
                        <?php foreach($this->view->all_acoes as $id => $acoes) { ?>
                            <?php if(empty($ant_cat)){
                                $ant_cat = array($acoes['categoria']);
                            ?>
                            <option value="<?=$acoes['categoria']?>"><?=$acoes['categoria']?></option>
                            <?php
                            }else{
                                if (!in_array($acoes['categoria'], $ant_cat)) {?>          
                                    <option value="<?=$acoes['categoria']?>"><?=$acoes['categoria']?></option>
                                <?php 
                                $ant_cat[] = $acoes['categoria'];
                                } 
                            } ?>
                        <?php }  ?>
                        <!--<option value="Doação de sangue">Doação de sangue</option>
                        <option value="Doação de suprimentos">Doação de suprimentos</option>
                        <option value="Distribuição suprimentos">Distribuição suprimentos</option>
                        <option value="Adoção de animais">Adoção de animais</option>
                        <option value="Passeio com animais">Passeio com animais</option>-->
                    </select>
                    <div >
                        <button type="submit" class="btn btn-light corBotao">Aplicar filtros</button>
                    </div>
                    <br>
                    <!--<a href="#" name="btnFiltro" id="btnFiltro" class="btn btn-light corBotao">Aplicar filtros</a>-->
                </div>
            </form>
        </div>
    </div>

    <!-- (FIM)lateral - Dados do usuário e filtro de pesquisa(ESQUERDA) -->

    <!--MEIO - Ações criadas pelos usuários -->
    <div class="acoes mt-5">
        <div class="row row-cols-1 cols-ms-6 g-4" id="acoesGeral">
          <?php foreach($this->view->all_acoes as $id => $acoes) { ?>
            <div class="col">
                <div class="card h-100 acoesCard">
                    <div class="userCard">
                        <?php if(empty($acoes['imagem_url'])) {?>
                            <img src="img/íconePerfil.jpg" alt="" class="img-fluid rounded-circle mb-2 fotoCard">
                        <?php } else
                                     if (file_exists('upload/perfil/'. $acoes['imagem_url'])) { ?>
                                        <img src="upload/perfil/<?= $acoes['imagem_url'] ?>" alt="" class="img-fluid rounded-circle mb-2 fotoCard">
                                    <?php } ?>
                        <a href="/perfilSecundario?id_usuario=<?=$acoes['id_usuario']?>" class="text-light"> <label class="nomeCard"><?=$acoes['nome']?></label></a>
                        <p class="dataCard">Criado em: <?= date('d/m/Y H:i', strtotime($acoes['data_criacao'])) ?></p>
                    </div>
                    
                    <?php if(empty($acoes['imagem'])) {?>
                        <img src="img/acaoSocial2.jpg" class="card-img-top" alt="...">
                        <?php } else
                                if (file_exists('upload/acao/'. $acoes['imagem'])) { ?>
                                    <img src="upload/acao/<?=$acoes['imagem']?>" class="card-img-top" alt="...">
                                <?php } ?>
                    <div class="card-body">
                        <a href="/participantes_acoes?id_acao=<?=$acoes['id']?>" class="text-light">
                            <p class="qtd_part"><?=$acoes['qtd_participantes']?></p>
                            <span class="material-icons qtd_part_ic">person</span>
                        </a> 
                        <h5 class="card-title"><?=$acoes['titulo']?></h5>
                        <p class="card-text"><?=$acoes['descricao']?></p>
                        <?php $dataInput = date('d-m-Y H:i:s', strtotime($acoes['data_evento'])); ?>
                        <p class="text-light">Data: <?= $dataInput ?></p>   
                        <?php if($acoes['participando_sn'] == 0) { ?> 
                            <a href="/action?action=participar&id_acao=<?=$acoes['id']?>" class="btn btn-light corBotao acoesBtn">Participar</a>
                        <?php } ?>
                        <?php if($acoes['participando_sn'] >= 1) { ?> 
                            <a href="/action?action=deixar_de_participar&id_acao=<?=$acoes['id']?>" class="btn btn-light corBotao acoesBtn">Deixar de Participar</a>
                     <?php } ?>   
                        <a href="#" class="btn btn-light corBotao acoesBtn" data-bs-toggle="modal" data-bs-target="#detalhes<?=$acoes['id']?>">Detalhes</a>
                    </div>
                    <hr>
                    <div class="card-body">
                        <input type="text" class="form-control bg-dark text-light w-75" name="nome_usuario" value="" placeholder="Escreva um comentário..." id="textbox-comentario-<?=$acoes['id']?>" style="float: left; padding: 10px;" aria-label="Recipient's username" aria-describedby="button-addon2">
                            <input type="hidden" id="id_usuario_logado" value="<?=$_SESSION['id']?>">
                            <button onclick="enviarComentario(<?=$acoes['id']?>)" class="btn corBotao" type="button" id="botao-comentario-<?=$acoes['id']?>"> 
                                <span class="material-icons text-light mt-1">arrow_forward_ios</span>
                            </button>
                            <div id="div-atualizar-<?=$acoes['id']?>">
                            </div>
                            <small id="resposta-<?=$acoes['id']?>"></small>
                            <button onclick="buscarComentarios(<?=$acoes['id']?>);" class="text-light mt-1 btnComentario" id="btn-mostrar-comentario<?=$acoes['id']?>">mostrar comentarios</button>
                            <button onclick="ocultarComentarios(<?=$acoes['id']?>);" class="text-light mt-1 btnComentario" id="btn-ocultar-comentario<?=$acoes['id']?>" style="display: none;">ocultar comentarios</button>
                            <div class="comentarios-<?=$acoes['id']?>"> 
                                <div class="w-100 mt-3 box-comentario" style="display: none;">
                                <div id="caixa-imagem-comentario" ></div>
                                    <div  class="caixaComentarios">
                                        <div class="editar_excluir">
                                            <label for="comentario">Editar</label>
                                            |
                                            <span  id="" class="text-light btn-deletar">Deletar</span>
                                        </div>
                                        <label class="nomeComentario">User Name</label>
                                        <p id="cx_comentarios"> </p>
                                    </div>
                                </div>
                            </div>
                    </div>
                </div>
            </div>
            <?php } ?>
        </div>
    </div>
    <!-- (FIM) MEIO - Ações criadas pelos usuários -->

    <!-- Anúncio -->
    <div class="anuncio">
        <div class="card mt-3 cardDireita">
            <div class="card-body text-light">
                <img src="img/anuncio.jpg" width="100%" height="471px"/>
            </div>
        </div>
    </div>
    <!-- (FIM) Anúncio -->


<!-- MODAL VER DETALHES DA AÇÃO -->
<?php foreach($this->view->all_acoes as $id => $acoes) { ?>
    <div class="modal" id="detalhes<?=$acoes['id']?>" tabindex="-1">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title"></h5>
              <button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <form class="form"> 
                <div class="modal-body">
                    <img src="upload/acao/<?=$acoes['imagem']?>" class="card-img-top" alt="...">
                    <div class="card-body">
                        <p class="qtd_part text-light"><?=$acoes['qtd_participantes']?></p>
                        <span class="material-icons qtd_part_ic text-light">person</span>
                        <h5 class="card-title text-light"><?=$acoes['titulo']?></h5>
                        <p class="card-text text-light"><?=$acoes['descricao']?></p>
                        <?php $dataInput = date('d-m-Y H:i:s', strtotime($acoes['data_evento'])); ?>
                        <p class="text-light"><?=$dataInput?></p>
                        <label>
                            <p class="text-light">Endereço: </p> 
                            <p id="ruaModal" name="ruaModal" class="text-light"><?=$acoes['logradouro']?>, </p> 
                        </label>
                        <label>
                            <p id="bairroModal" name="bairroModal" class="text-light"><?=$acoes['bairro']?>, </p>
                        </label>
                         <label>
                             <p id="cidadeModal" name="cidadeModal" class="cidadeNum text-light"><?=$acoes['cidade']?>, </p>
                        </label>
                        <label>
                            <p id="ufModal" name="ufModal" class="ufNum text-light"><?=$acoes['uf']?></p>
                        </label>
                    </div>
                </div>   
            </form>    
          </div>
        </div>
    </div>    
    <?php } ?>
    <!-- (FIM) MODAL VER DETALHES DA AÇÃO -->
</body>

</html>