<!DOCTYPE html>
<html lang="pt-BR">

<head>
    <title>Voluntarie.se | Feed</title>
    <link rel="stylesheet" href="css/feed.css">
    <link rel="stylesheet" href="cssResp/feedResp.css">
    <link rel="stylesheet" href="cssResp/BarraMobResp.css">
    <link rel="stylesheet" href="css/navBarPC.css">
</head>

<body>
     
    <!-- Lateral - Dados do usuário e filtro de pesquisa(ESQUERDA) -->
    <div class="perfilFiltro">
        <div class="card mt-3 cardEsquerda" id="cardPerfil">
            <div class="card-body">
                <img src="img/íconePerfil.jpg" alt="" class="img-fluid rounded-circle mb-2" id="fotoPerfil">
                <h4 class="mb-5 text-light"><?=$_SESSION['nome']?></h4>
                <a href="meu_perfil" class="btn btn-light corBotao mb-4">Meu perfil</a>
            </div>
        </div>
        <div class="card mt-4 cardEsquerda" id="cardFiltro">
            <div class="card-body filtro">
                <h6 class="tituloFiltro text-light">Filtro de pesquisa <i class="fas fa-filter"></i></h6>
                <p class="text-light mb-1">Cidade:</p>
                <input type="text" class="form-control bg-dark p-0 text-light" id="cidade">
                <p class="mt-1 text-light mb-1">Estado:</p>
                <select class="form-select bg-dark text-light mb-0 p-0" aria-label="Default select example" name="estado">
                    <option disabled="disabled" selected="selected">-Selecione uma opção</option>
                    <option value="1">AL</option>
                    <option value="2">AM</option>
                    <option value="3">BA</option>
                    <option value="4">CE</option>
                    <option value="5">PB</option>
                    <option value="6">PE</option>
                </select>
                <p class="mt-1 text-light mb-1">Categoria:</p>
                <select class="form-select bg-dark text-light p-0 mb-3" aria-label="Default select example" name="categoria">
                    <option disabled="disabled" selected="selected">-Selecione uma opção</option>
                    <option value="1">Visitações</option>
                    <option value="2">Doação de sangue</option>
                    <option value="3">Doação de suprimentos</option>
                    <option value="4">Distribuição suprimentos</option>
                    <option value="5">Adoção de animais</option>
                    <option value="6">Passeio com animais</option>
                </select>
                <a href="#" name="btnFiltro" id="btnFiltro" class="btn btn-light corBotao">Aplicar filtros</a>
            </div>
        </div>
    </div>

    <!-- (FIM)lateral - Dados do usuário e filtro de pesquisa(ESQUERDA) -->

    <!--MEIO - Ações criadas pelos usuários -->
    <div class="acoes mt-5">
        <div class="row row-cols-1 cols-ms-6 g-4" id="acoesGeral">
          <?php foreach($this->view->all_acoes as $id => $acoes) { ?>
            <div class="col">
                <div class="card h-100 acoesCard">
                    <div class="userCard">
                        <img src="img/íconePerfil.jpg" alt="" class="img-fluid rounded-circle mb-2 fotoCard">
                        <label class="nomeCard"><?=$acoes['nome']?></label>
                        <p class="dataCard">Criado em: <?= date('d/m/Y H:i', strtotime($acoes['data_criacao'])) ?></p>
                    </div>
                    <img src="img/acaoSocial2.jpg" class="card-img-top" alt="...">
                    <div class="card-body">
                        <p class="qtd_part">0</p>
                        <span class="material-icons qtd_part_ic">person</span>
                        <h5 class="card-title"><?=$acoes['titulo']?></h5>
                        <p class="card-text"><?=$acoes['descricao']?></p>
                        <p class="text-light">Data: 15/07/2021</p>    
                        <a href="#" class="btn btn-light corBotao acoesBtn">Participar</a>
                        <a href="#" class="btn btn-light corBotao acoesBtn" data-bs-toggle="modal" data-bs-target="#detalhes">Detalhes</a>
                    </div>
                </div>
            </div>
            <?php } ?>
        </div>
    </div>
    <!-- (FIM) MEIO - Ações criadas pelos usuários -->

    <!-- Anúncio -->
    <div class="anuncio">
        <div class="card mt-3 cardDireita">
            <div class="card-body text-light">
                <p>ANÚNCIO</p>
            </div>
        </div>
    </div>
    <!-- (FIM) Anúncio -->


    <!-- MODAL VER DETALHES DA AÇÃO -->
    <div class="modal" id="detalhes" tabindex="-1">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title"></h5>
              <button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <form class="form"> 
                <div class="modal-body">
                    <img src="img/acaoSocial2.jpg" class="card-img-top" alt="...">
                    <div class="card-body">
                        <p class="qtd_part text-light">0</p>
                        <span class="material-icons qtd_part_ic text-light">person</span>
                        <h5 class="card-title text-light">Card title</h5>
                        <p class="card-text text-light">This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
                        <p class="text-light">Data: 15/07/2021</p>
                        <label>
                            <p class="text-light">Endereço: </p>
                            <p id="ruaModal" name="ruaModal" class="text-light"> Rua tabelião João Lago, </p> 
                        </label>
                        <label>
                            <p id="numModal" name="numModal" class="text-light"> 195, </p>
                        </label>
                        <label>
                            <p id="cepModal" name="cepModal" class="cepNum text-light"> 54740-710, </p> 
                        </label>
                        <label>
                            <p id="bairroModal" name="bairroModal" class="text-light">Capibaribe</p>
                        </label>
                         <label>
                             <p id="cidadeModal" name="cidadeModal" class="cidadeNum text-light">São lourenço da Mata, </p>
                        </label>
                        <label>
                            <p id="ufModal" name="ufModal" class="ufNum text-light">PE</p>
                        </label>
                    </div>
                </div>   
            </form>    
            <div class="modal-footer">
              <button type="button" class="btn btn-light corBotao">Participar</button>
            </div>
          </div>
        </div>
    </div>    
    <!-- (FIM) MODAL VER DETALHES DA AÇÃO -->
</body>

</html>