<!DOCTYPE html>
<html lang="pt-BR">

<head>
    <title>Voluntarie.se | Perfil</title>
    <link rel="stylesheet" href="css/perfil.css">
    <link rel="stylesheet" href="cssResp/BarraMobResp.css">
    <link rel="stylesheet" href="cssResp/perfilResp.css">
    <script src="JavaScript/perfil.js"></script>
</head>

<body>

    <!-- Body Perfil -->
    <?php foreach ($this->view->info_usuario as $id => $info) { ?>
        <div class="perfil m-auto mt-5">
            <?php  if (empty($this->view->minha_imagem)) { ?>
                    <div class="fotoPerfil">
                    <img src="img/íconePerfil.jpg" alt="" class="img-fluid rounded-circle" id="fotoPerfil">
                    <button id="editarImagem" data-bs-toggle="modal" data-bs-target="#alterarFoto"><span class="material-icons text-light" id="icon">camera_alt</span></button>
                    </div>
              <?php  } ?>
              <?php foreach ($this->view->minha_imagem as $id => $imagem) { ?>
                <div class="fotoPerfil">
                    <?php if (file_exists('upload/perfil/'. $imagem['imagem_url'])) { ?>
                        <img src="upload/perfil/<?= $imagem['imagem_url'] ?>" alt="" class="img-fluid rounded-circle" id="fotoPerfil">
                    <?php } else { ?>  
                        <img src="img/íconePerfil.jpg" alt="" class="img-fluid rounded-circle" id="fotoPerfil">  
                    <?php } ?>    
                    <button id="editarImagem" data-bs-toggle="modal" data-bs-target="#alterarFoto"><span class="material-icons text-light" id="icon">camera_alt</span></button>
                </div>
            <?php } ?>
            <div class="dadosPerfil">
                <div id="dadosPerfil">
                    <h3 class="text-light"><?= $info['nome'] ?></h3>
                    <label class="text-light mt-3 mb-3"><strong><?= $info['n_acoes'] ?></strong> ações publicadas</label>
                    <p class="text-light"><?= $info['email'] ?></p>
                    <p class="text-light"><?= $info['telefone'] ?></p>
                </div>
                <div>
                    <button class="btn btn-light corBotao p-1" type="button" id="botaoEditar" data-bs-toggle="modal" data-bs-target="#editarDados<?= $info['id'] ?>">Editar dados</button>
                </div>
            </div>
        </div>

        <!-- Modal Editar dados -->
        <div class="modal" id="editarDados<?= $info['id'] ?>" tabindex="-1">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title text-light">Editar Dados</h5>
                        <button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <form class="form" id="alterar">
                        <div class="modal-body">
                            <div class="mb-2">
                                <label class="form-label text-light mb-0">Nome</label>
                                <input type="text" class="form-control bg-dark text-light p-1" id="nome" value="<?= $info['nome'] ?>" name="nome">
                            </div>
                            <div class="mb-2">
                                <label class="form-label text-light mb-0">Telefone</label>
                                <input type="text" class="form-control bg-dark text-light p-1" id="telefone" value="<?= $info['telefone'] ?>" name="telefone">
                            </div>
                            <div class="mb-2">
                                <label class="form-label text-light mb-0">Data de nascimento</label>
                                <input type="date" class="form-control bg-dark text-light p-1" id="data" name="data" min="1920-01-01" max="2020-12-31">
                            </div>
                            <div class="mb-2">
                                <label class="form-label text-light mb-0">Sexo</label>
                                <select class="form-select bg-dark text-light p-1" aria-label="Default select example" name="sexo">
                                    <option disabled="disabled" selected="selected">- Selecione uma opção</option>
                                    <option value="F">Feminimo</option>
                                    <option value="<?= $info['sexo'] ?>">Masculino</option>
                                </select>
                            </div>
                        </div>
                    </form>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-light corBotao">Salvar</button>
                    </div>
                </div>
            </div>
        </div>
        <!-- FIM - Modal Editar dados -->

    <?php } ?>

   <!-- Modal FOTO DO PERFIL -->
   <div class="modal" id="alterarFoto" tabindex="-1">
      <form action="/meu_perfil" method="post" enctype="multipart/form-data" class="form">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title text-light">Foto do Perfil</h5>
                    <button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <input class="form-control bg-dark text-light" type="file" name="imagem_perfil"  onchange="previewImagem()">
                    <img name="imagemPerfil" id="image">
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-light corBotao">Salvar foto</button>
                </div>
            </div>
        </div>
      </form>
    </div>
    <!-- FIM - Modal FOTO DO PERFIL -->

    <nav class="nav_tabs" style="background-color: #1b1c1f;">
        <ul>
            <li>
                <input type="radio" name="tabs" class="rd_tabs" id="tab1" checked>
                <label for="tab1" class="opcoes">Minhas Ações</label>
                <div class="acao">
                    <article class="pb-3">
                        <div class="acoes mt-2">
                            <div class="row row-cols-1 row-cols-md-3 g-4" id="acoesGeral">
                                <?php date_default_timezone_set('America/Sao_Paulo') ?>
                                    <?php foreach ($this->view->minhas_acoes as $id_acoes => $acao) { ?>
                                        <div class="col">
                                            <div class="card h-100 acoesCard">
                                            <div class="userCard">
                                                <?php if(empty($this->view->minha_imagem)) { ?>
                                                    <img src="img/íconePerfil.jpg" alt="" class="img-fluid rounded-circle mb-2 fotoCard">
                                                <?php } else 
                                                            foreach($this->view->minha_imagem as $id => $imagem)  { 
                                                                 if (file_exists('upload/perfil/'. $imagem['imagem_url'])) {  ?>
                                                                    <img src="upload/perfil/<?= $imagem['imagem_url'] ?>" alt="" class="img-fluid rounded-circle mb-2 fotoCard">
                                                                  <?php }else { ?>  
                                                                        <img src="img/íconePerfil.jpg" alt="" class="img-fluid rounded-circle mb-2" id="fotoPerfil">
                                                                    <?php } ?>
                                                            <?php } ?>      
                                                        <label class="nomeCard"> <?=$_SESSION['nome'] ?></label>
                                                        <p class="dataCard">Criado em: <?php echo date('d/m/Y H:i', strtotime($acao['data_criacao'])) ?></p>
                                                    </div>
                                

                                             
                
                                                    <img src="img/acaoSocial2.jpg" class="card-img-top" alt="...">
                                                     
                                                <div class="card-body d-flex flex-column align-items-left">
                                                    <h5 class="card-title"> <?= $acao['titulo'] ?></h5>
                                                    <p class="card-text"><?=$acao['descricao'] ?></p>
                                                    <p class="qtd_part"> 0 <span class="material-icons qtd_part_ic">person</span></p>
                                                        <div class="mt-auto botaoesCards">
                                                            <a href=""  type="submit" class="btn btn-light corBotao acoesBtn" data-bs-toggle="modal" data-bs-target="#exampleModal<?= $acao['id'] ?>">Editar</a>
                                                            <form method="POST" action="/remover_acao" class="form acoesBtn" style="float: right; margin-left: 1px;">
                                                                <button type="submit" name="id" value="<?php echo $acao['id'] ?>" class="btn btn-light corBotao w-100"> Delete </button>
                                                            </form>
                                                        </div>
                                                </div>
                                            </div>
                                        </div>
                                                    <!-- Modal Editar Ações -->

                                        <div class="modal fade" id="exampleModal<?= $acao['id'] ?>" tabindex="-1">
                                            <div class="modal-dialog modal-lg">
                                                <div class="modal-content">
                                                    <div class="modal-header">
                                                        <h5 class="modal-title text-light">Editar Ação</h5>
                                                        <button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal" aria-label="Close"></button>
                                                    </div>
                                                    <form class="form formulario p-3" id="alterar">
                                                        <div class="mb-3">
                                                            <label class="form-label text-light mt-3">Título</label>
                                                            <input type="text" value="<?= $acao['titulo'] ?>" class="form-control bg-dark text-light" id=" exampleFormControlInput1" required>
                                                        </div>
                                                        <div class="mb-3">
                                                            <label class="form-label text-light">Descrição</label>
                                                            <textarea class="form-control bg-dark text-light" id="exampleFormControlTextarea1" rows="3" required></textarea>
                                                        </div>
                                                        <div class="mb-3 w-50 left">
                                                            <label class="form-label text-light">Data</label>
                                                            <input type="datetime-local" class="form-control bg-dark text-light" id="data" min="2021-06-24T00:00:00" required>
                                                        </div>
                                                        <div class="mb-3 w-50 left">
                                                            <label class="form-label text-light">Categoria</label>
                                                            <select class="form-select bg-dark text-light" aria-label="Default select example" name="categoria" required>
                                                                <option disabled="disabled" selected="selected">-- Selecione uma opção</option>
                                                                <option value="1">Visitações</option>
                                                                <option value="2">Doação de sangue</option>
                                                                <option value="3">Doação de suprimentos</option>
                                                                <option value="4">Distribuição suprimentos</option>
                                                                <option value="5">Adoção de animais</option>
                                                                <option value="6">Passeio com animais</option>
                                                            </select>
                                                        </div>
                                                        <div id="quadrado">
                                                            <label for="formFile" class="form-label text-light">Endereço</label>
                                                            <div class="input-group mb-3">
                                                                <input type="text" class="form-control bg-dark text-light" placeholder="Cep" id="cep" required>
                                                                <button class="btn corBotao btn-light" type="button" id="obterEndereco" onclick="endereco()">Obter Endereço</button>
                                                            </div>

                                                            <div class="mb-3">
                                                                <input type="text" class="form-control bg-dark text-light" placeholder="Logradouro" aria-label="Recipient's username" aria-describedby="button-addon2" id="logradouro" name="logradouro" required>
                                                            </div>
                                                            <div class="mb-3">
                                                                <input type="text" class="form-control bg-dark text-light" placeholder="Complemento" aria-label="Recipient's username" aria-describedby="button-addon2" id="complemento" name="complemento">
                                                            </div>

                                                            <div class="mb-3">
                                                                <input type="text" class="form-control bg-dark text-light" placeholder="Bairro" aria-label="Recipient's username" aria-describedby="button-addon2" id="bairro" name="bairro" required>
                                                            </div>

                                                            <div class="mb-3">
                                                                <input type="text" class="form-control bg-dark text-light" placeholder="Cidade" aria-label="Recipient's username" aria-describedby="button-addon2" id="localidade" name="cidade" required>
                                                            </div>

                                                            <div class="mb-3">
                                                                <input type="text" class="form-control bg-dark text-light" placeholder="Estado" aria-label="Recipient's username" aria-describedby="button-addon2" id="uf" name="uf" required>
                                                            </div>
                                                        </div>

                                                        <div class="mb-3">
                                                            <label for="formFile" class="form-label text-light">Imagem</label>
                                                            <input class="form-control bg-dark text-light" type="file" name="imagem" id="escolherImagem" onchange="previewImagem()">
                                                        </div>
                                                    </form>
                                                    <div class="modal-footer">
                                                        <button type="button" class="btn btn-light corBotao">Alterar</button>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                                <!-- FIM - Modal Editar Ações -->
                                    <?php } ?>
                            </div>
                    </article>
                </div>
            </li>
            <li>
                <input type="radio" name="tabs" class="rd_tabs" id="tab2">
                <label for="tab2" class="opcoes">Ações que participo</label>
                <div class="acao">
                    <article class="pb-3">
                        <div class="acoes mt-2">
                            <div class="row row-cols-1 row-cols-md-3 g-4" id="acoesGeral">
                                <?php foreach($this->view->acoes_que_participo as $id => $participo) { ?>   
                                    <div class="col">
                                        <div class="card h-100 acoesCard">
                                            <div class="userCard">
                                                <?php if (empty($participo['imagem_url'])) { ?>
                                                    <img src="img/íconePerfil.jpg" alt="" class="img-fluid rounded-circle mb-2 fotoCard">
                                                <?php } else { ?>  
                                                    <img src="upload/perfil/<?= $participo['imagem_url'] ?>" alt="" class="img-fluid rounded-circle mb-2 fotoCard">
                                                <?php } ?>    
                                                <label class="nomeCard"><?=$participo['nome'] ?></label>
                                                <p class="dataCard">Criado em: <?php echo date('d/m/Y H:i', strtotime($participo['data_criacao'])) ?></p>
                                            </div>
                                            <?php if (empty($participo['imagem'])) { ?>
                                                <img src="img/acaoSocial2.jpg" class="card-img-top" alt="...">
                                            <?php }else { ?>
                                                <img src="upload/acao/<?=$participo['imagem']?>" class="card-img-top" alt="...">
                                            <?php } ?>        
                                            <div class="card-body d-flex flex-column align-items-left">
                                                <h5 class="card-title"><?=$participo['titulo']?></h5>
                                                <p class="card-text"><?=$participo['descricao']?></p>
                                                <p class="qtd_part"> 0 <span class="material-icons qtd_part_ic">person</span></p>
                                                <div class="mt-auto">
                                                    <a href="#" class="btn btn-light corBotao acoesBtn">Remover</a>
                                                    <a href="#" class="btn btn-light corBotao acoesBtn" data-bs-toggle="modal" data-bs-target="#detalhes">Detalhes</a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                <?php } ?>
                            </div>
                        </div>
                    </article>
                </div>
            </li>
        </ul>
    </nav>

    <!-- MODAL VER DETALHES DA AÇÃO -->
    <div class="modal" id="detalhes" tabindex="-1">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title"></h5>
                    <button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <form class="form">
                    <div class="modal-body">
                        <img src="img/acaoSocial2.jpg" class="card-img-top" alt="...">
                        <div class="card-body">
                            <p class="qtd_part text-light">0</p>
                            <span class="material-icons qtd_part_ic text-light">person</span>
                            <h5 class="card-title text-light">Card title</h5>
                            <p class="card-text text-light">This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
                            <p class="text-light">Data: 15/07/2021</p>
                            <label>
                                <p class="text-light">Endereço: </p>
                                <p id="ruaModal" name="ruaModal" class="text-light"> Rua tabelião João Lago, </p>
                            </label>
                            <label>
                                <p id="numModal" name="numModal" class="text-light"> 195, </p>
                            </label>
                            <label>
                                <p id="cepModal" name="cepModal" class="cepNum text-light"> 54740-710, </p>
                            </label>
                            <label>
                                <p id="bairroModal" name="bairroModal" class="text-light">Capibaribe</p>
                            </label>
                            <label>
                                <p id="cidadeModal" name="cidadeModal" class="cidadeNum text-light">São lourenço da Mata, </p>
                            </label>
                            <label>
                                <p id="ufModal" name="ufModal" class="ufNum text-light">PE</p>
                            </label>
                        </div>
                    </div>
                </form>
                <div class="modal-footer">
                    <button type="button" class="btn btn-light corBotao">Remover</button>
                </div>
            </div>
        </div>
    </div>
    <!-- (FIM) MODAL VER DETALHES DA AÇÃO -->

</body>

</html>