<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <link rel="stylesheet" href="/css/index.css">
    <link rel="stylesheet" href="/cssResp/indexResp.css">
    <title>Voluntarie.se | Bem-vindo ao Voluntarie</title>
    <link rel="apple-touch-icon" sizes="180x180" href="/img/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/img/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/img/favicon-16x16.png">
    <link rel="manifest" href="/img/site.webmanifest">
    <link href="/bootstrap-5.0.0-beta2-dist/bootstrap-5.0.0-beta2-dist/css/bootstrap.min.css" rel="stylesheet"
        type="text/css">
    <script type="text/javascript" src="/js/jquery-3.5.1.min.js"> </script>
    <script type="text/javascript" src="/js/bootstrap.min.js"> </script>
    <script type="text/javascript" src="/js/jquery.validate.min.js"> </script>
    <script type="text/javascript" src="/js/additional-methods.min.js"> </script>
    <script type="text/javascript" src="/js/localization/messages_pt_BR.js"></script>
    <script type="text/javascript" src="/js/jquery.mask.min.js"></script>
    <script src="/JavaScript/index.js"></script>


</head>
<body>

  
    <?= $this->content() ?>

</body>
</html>